### ISSUE TITLE
How can I use this as a CLI Tool to control basic Settings? 

### ISSUE THREAD

**Issue by mattyg-repo** [pixeltris/SonyAlphaUSB#3]
your work is exactly that what I am looking for.
can you please help me? 

THANK You

**Comment by pixeltris** [comment]
Unfortunately I never really finished my work on this so it's not really set up to be used in any productive way.

gphoto2 supports Sony Alpha cameras and is CLI-focused. If you're running on Windows and can't find a Windows build then you could run it under WSL (Windows Subsystem for Linux).

**Comment by mattyg-repo** [comment]
okay.  thanks for your response and your work
